targets:
  $default:
    builders:
      freezed:
        options:
          copy_with: false
          to_json: false
      json_serializable:
        options:
          explicit_to_json: true
      drift_dev:
        options:
          store_date_time_values_as_text: true