name: foxcord_common
version: 1.0.0
description: Common code for all FoxCord backend services.
repository: https://git.kasefuchs.su/foxcordchat/backend
issue_tracker: https://git.kasefuchs.su/foxcordchat/backend/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  base32: ^2.1.3
  dart_amqp: ^0.2.5
  dart_mappable: ^4.2.0
  dartfield: ^1.1.0
  drift: ^2.14.1
  drift_postgres: ^1.0.0
  foxid: ^1.1.1
  freezed_annotation: ^2.4.1
  postgres: ^3.0.4

dev_dependencies:
  build_runner: ^2.4.7
  dart_mappable_builder: ^4.2.0
  drift_dev: ^2.14.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.0

publish_to: none

funding:
  - https://boosty.to/kasefuchs

topics:
  - foxcord
  - foxcordchat
