name: foxcord_common
version: 1.0.0
description: Common code for all FoxCord backend services.
repository: https://git.kasefuchs.su/foxcordchat/backend
issue_tracker: https://git.kasefuchs.su/foxcordchat/backend/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  orm: ^3.4.4

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0

publish_to: none

funding:
  - https://boosty.to/kasefuchs

topics:
  - foxcord
  - foxcordchat
