name: foxcord_backend

packages:
  - packages/*

command:
  bootstrap:
    hooks:
      post: melos run buf:generate && melos run build_runner:build

scripts:
  build_runner:build:
    run: dart run build_runner build --delete-conflicting-outputs --low-resources-mode
    exec:
      orderDependents: true
    description: Run a build_runner build.
    packageFilters:
      dependsOn:
        - build_runner

  build_runner:watch:
    exec: dart run build_runner watch --delete-conflicting-outputs --low-resources-mode
    description: Run a build_runner watch.
    packageFilters:
      dependsOn:
        - build_runner

  test:
    exec: dart test
    description: Run Dart tests.
    packageFilters:
      dirExists:
        - test
      dependsOn:
        - test

  buf:generate:
    run: buf generate
    exec:
      orderDependents: true
    description: Generate code with protoc plugins.
    packageFilters:
      fileExists:
        - buf.yaml
        - buf.gen.yaml
      dependsOn:
        - protobuf

ide:
  intellij:
    moduleNamePrefix: ""
