name: foxcord_backend

packages:
  - packages/*

command:
  bootstrap:
    hooks:
      post: melos run prisma:generate && melos run build_runner:build

scripts:
  build_runner:build:
    run: |
      melos exec -- \
        "dart run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build.
    packageFilters:
      dependsOn:
        - build_runner

  build_runner:watch:
    run: |
      melos exec -- \
        "dart run build_runner watch --delete-conflicting-outputs"
    description: Run a build_runner watch.
    packageFilters:
      dependsOn:
        - build_runner

  prisma:generate:
    run: |
      melos exec -- \
        "yarn prisma:generate"
    description: Generate Prisma Client.
    packageFilters:
      dirExists:
        - prisma
      dependsOn:
        - orm

  prisma:push:
    run: |
      melos exec -- \
        "yarn prisma:push"
    description: Push Prisma schema to database.
    packageFilters:
      dirExists:
        - prisma
      dependsOn:
        - orm

  test:
    run: |
      melos exec -- \
        "dart test"
    description: Run Dart tests.
    packageFilters:
      dirExists:
        - test
      dependsOn:
        - test

ide:
  intellij:
    moduleNamePrefix: ""
