name: foxcord_api
version: 1.0.0
description: FoxCord REST API server.
repository: https://git.kasefuchs.su/foxcordchat/backend
issue_tracker: https://git.kasefuchs.su/foxcordchat/backend/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  foxcord_common: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

publish_to: none

funding:
  - https://boosty.to/kasefuchs

topics:
  - foxcord
  - foxcordchat
