name: foxcord_api
version: 1.0.0
description: FoxCord REST API server.
repository: https://git.kasefuchs.su/foxcordchat/backend
issue_tracker: https://git.kasefuchs.su/foxcordchat/backend/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  foxcord_common: ^1.0.0
  minerva: ^0.3.6
  minerva_controller_annotation: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  minerva_controller_generator: ^0.9.5
  lints: ^2.0.0
  test: ^1.21.0

publish_to: none

funding:
  - https://boosty.to/kasefuchs

topics:
  - foxcord
  - foxcordchat
