name: Repo Lockdown

on:
  pull_request_target:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          pr-comment: >-
            Hi! Thank you for your contribution.

            This repo is only a mirror and unfortunately we can't accept PRs made here. Please re-submit your changes to [our Forgejo instance](https://git.kasefuchs.su/foxcordchat/backend/pulls).

            Thank you for your understanding.
